# Generated by Django 2.0.3 on 2018-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION cube', reverse_sql='DROP EXTENSION cube'),
        migrations.RunSQL('CREATE EXTENSION earthdistance', reverse_sql='DROP EXTENSION earthdistance'),
    ]
